# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jan/git/udp_communication/fpga/config/pins.xdc

# Block Designs: bd/blinking/blinking.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking || ORIG_REF_NAME==blinking} -quiet] -quiet

# IP: bd/blinking/ip/blinking_led_blinking_0_0/blinking_led_blinking_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_led_blinking_0_0 || ORIG_REF_NAME==blinking_led_blinking_0_0} -quiet] -quiet

# IP: bd/blinking/ip/blinking_clk_wiz_0_0/blinking_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_clk_wiz_0_0 || ORIG_REF_NAME==blinking_clk_wiz_0_0} -quiet] -quiet

# IP: bd/blinking/ip/blinking_xlconstant_1_0/blinking_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_xlconstant_1_0 || ORIG_REF_NAME==blinking_xlconstant_1_0} -quiet] -quiet

# IP: bd/blinking/ip/blinking_proc_sys_reset_0_0/blinking_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinking_proc_sys_reset_0_0 || ORIG_REF_NAME==blinking_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/blinking/blinking_ooc.xdc
